/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import materiales.CrearMaterial;

/**
 *
 * @author José Eduardo
 */
public class RegistrarMaterial extends javax.swing.JFrame {

    /**
     * Creates new form AgregarMaterial
     */
    public RegistrarMaterial() {
        initComponents();
        setLocationRelativeTo(null);
        lblCaracteristicaDeMaterial.setVisible(false);
        txtFCaracteristicaDeMaterial.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    txtFFolio = new javax.swing.JTextField();
    txtFEditorial = new javax.swing.JTextField();
    txtFFechaDePublicacion = new javax.swing.JTextField();
    txtFTitulo = new javax.swing.JTextField();
    txtFPrecio = new javax.swing.JTextField();
    lblFolio = new javax.swing.JLabel();
    lblTipoDeMaterial = new javax.swing.JLabel();
    lblEditorial = new javax.swing.JLabel();
    lblFechaDePublicacion = new javax.swing.JLabel();
    lblTitulo = new javax.swing.JLabel();
    lblPrecio = new javax.swing.JLabel();
    cbTipoDeMaterial = new javax.swing.JComboBox<>();
    jLabel10 = new javax.swing.JLabel();
    btnCerrarSesion = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    btnGuardar = new javax.swing.JButton();
    btnCancelar = new javax.swing.JButton();
    lblCaracteristicaDeMaterial = new javax.swing.JLabel();
    txtFCaracteristicaDeMaterial = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));
    jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));

    lblFolio.setText("Folio:");

    lblTipoDeMaterial.setText("Tipo de material:");

    lblEditorial.setText("Editorial:");

    lblFechaDePublicacion.setText("Fecha de publicación:");

    lblTitulo.setText("Titulo:");

    lblPrecio.setText("Precio:");

    cbTipoDeMaterial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de Material...", "Libro", "Revista", "Software", "Mapa", "Medios opticos" }));
    cbTipoDeMaterial.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        cbTipoDeMaterialItemStateChanged(evt);
      }
    });

    jLabel10.setIcon(new javax.swing.JLabel() {
      public javax.swing.Icon getIcon() {
        try {
          return new javax.swing.ImageIcon(
            new java.net.URL("http://3.bp.blogspot.com/-6DU1m9msxsw/VxYod_e_eXI/AAAAAAAAADE/5WYpmfF4LaESgwBGBb0sJvzBMgveP-FKQCK4B/s1600/biblio.jpg")
          );
        } catch (java.net.MalformedURLException e) {
        }
        return null;
      }
    }.getIcon());
    jLabel10.setText("jLabel3");

    btnCerrarSesion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
    btnCerrarSesion.setText("Cerrar sesión");
    btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCerrarSesionActionPerformed(evt);
      }
    });

    jLabel5.setIcon(new javax.swing.JLabel() {
      public javax.swing.Icon getIcon() {
        try {
          return new javax.swing.ImageIcon(
            new java.net.URL("https://2.bp.blogspot.com/-U5Xd_10b7f8/VxkPgtZvl2I/AAAAAAAAADk/DKnbjLq6xqMeOkg-1DYdrHbcg_-bPjFrACLcB/s1600/user.png")
          );
        } catch (java.net.MalformedURLException e) {
        }
        return null;
      }
    }.getIcon());

    jLabel8.setText("Hola Usuario Ejemplo!");

    btnGuardar.setText("Guardar");
    btnGuardar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
      }
    });

    btnCancelar.setText("Cancelar");
    btnCancelar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCancelarActionPerformed(evt);
      }
    });

    lblCaracteristicaDeMaterial.setText("Caracteristica:");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
            .addComponent(jLabel8)
            .addGap(18, 18, 18)
            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(lblFolio)
                  .addComponent(lblTipoDeMaterial)
                  .addComponent(lblPrecio)
                  .addComponent(lblTitulo)
                  .addComponent(lblEditorial)
                  .addComponent(lblFechaDePublicacion)
                  .addComponent(lblCaracteristicaDeMaterial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(btnGuardar)
                .addGap(69, 69, 69)))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(cbTipoDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(btnCancelar)
                  .addComponent(txtFCaracteristicaDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addComponent(txtFFolio)
              .addComponent(txtFTitulo)
              .addComponent(txtFEditorial)
              .addComponent(txtFFechaDePublicacion))
            .addGap(157, 157, 157)
            .addComponent(btnCerrarSesion)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel8)
            .addGap(40, 40, 40)))
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnCerrarSesion)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtFFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblFolio))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(lblTipoDeMaterial)
              .addComponent(cbTipoDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblTitulo))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(lblEditorial)
              .addComponent(txtFEditorial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtFFechaDePublicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblFechaDePublicacion))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(txtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(lblPrecio))))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(txtFCaracteristicaDeMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(lblCaracteristicaDeMaterial))
        .addGap(26, 26, 26)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(btnGuardar)
          .addComponent(btnCancelar))
        .addContainerGap(94, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        InterfazPrincipal regresarinicio = new InterfazPrincipal();
        regresarinicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        
    }//GEN-LAST:event_btnCancelarActionPerformed

  private void cbTipoDeMaterialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTipoDeMaterialItemStateChanged
    lblCaracteristicaDeMaterial.setVisible(true);
    txtFCaracteristicaDeMaterial.setVisible(true);
    Object Material = cbTipoDeMaterial.getSelectedItem();
    String tipoDeMaterial = Material.toString();
    switch (tipoDeMaterial) {
      case "Libro":
        lblCaracteristicaDeMaterial.setText("Autor");
        break;
      case "Medios opticos":
        lblCaracteristicaDeMaterial.setText("CD, DVD o Blu-ray");
        break;
      case "Periodico":
        lblCaracteristicaDeMaterial.setText("Dia de la semana de publicación");
        break;
      case "Software":
        lblCaracteristicaDeMaterial.setText("Version");
        break;
      case "Mapa":
        lblCaracteristicaDeMaterial.setText("Tipo de Mapa");
        break;
      case "Revista":
        lblCaracteristicaDeMaterial.setText("Volumen");
        break; 
      default:
        lblCaracteristicaDeMaterial.setVisible(false);
        txtFCaracteristicaDeMaterial.setVisible(false);
        break;
    }
  }//GEN-LAST:event_cbTipoDeMaterialItemStateChanged

  private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String folio = txtFFolio.getText();
        String titulo = txtFTitulo.getText();
        String editorial = txtFEditorial.getText(); 
        String fechaDePublicacion = txtFFechaDePublicacion.getText(); 
        String precioIngresado = txtFPrecio.getText(); 
        String caracteristica = txtFCaracteristicaDeMaterial.getText();
        double precio = Double.parseDouble(precioIngresado);
        CrearMaterial registro = new CrearMaterial();
        Object material = cbTipoDeMaterial.getSelectedItem();
        String tipoDeMaterial = material.toString();
        registro.crearMaterial(folio, tipoDeMaterial, titulo, editorial, fechaDePublicacion, 
                precio, caracteristica);
        limpiarCampos();
  }//GEN-LAST:event_btnGuardarActionPerformed

  public void limpiarCampos(){
    txtFFolio.setText(" ");
    txtFTitulo.setText(" ");
    txtFEditorial.setText(" ");
    txtFFechaDePublicacion.setText(" ");
    txtFPrecio.setText(" ");
    txtFCaracteristicaDeMaterial.setText(" ");
    cbTipoDeMaterial.setSelectedItem("Tipo de Material...");
    lblCaracteristicaDeMaterial.setVisible(false);
    txtFCaracteristicaDeMaterial.setVisible(false);
  }
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarMaterial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarMaterial().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCancelar;
  private javax.swing.JButton btnCerrarSesion;
  private javax.swing.JButton btnGuardar;
  private javax.swing.JComboBox<String> cbTipoDeMaterial;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblCaracteristicaDeMaterial;
  private javax.swing.JLabel lblEditorial;
  private javax.swing.JLabel lblFechaDePublicacion;
  private javax.swing.JLabel lblFolio;
  private javax.swing.JLabel lblPrecio;
  private javax.swing.JLabel lblTipoDeMaterial;
  private javax.swing.JLabel lblTitulo;
  private javax.swing.JTextField txtFCaracteristicaDeMaterial;
  private javax.swing.JTextField txtFEditorial;
  private javax.swing.JTextField txtFFechaDePublicacion;
  private javax.swing.JTextField txtFFolio;
  private javax.swing.JTextField txtFPrecio;
  private javax.swing.JTextField txtFTitulo;
  // End of variables declaration//GEN-END:variables
}
